### ISSUE TITLE
Node.js - Create batch get, batch write, transact write, and transact read examples with node.js SDK

### ISSUE THREAD

**Issue by synchrophoto** [synchrophoto/DynamoDB-SDK-examples#1]
Create examples of each one of these calls for DynamoDB. The code should be the kind of simple example that  if you were a beginner, you'd see and say "This is a great example and exactly what I need!!" So the code is actionable, meaning a dev can use the example immediately.

This code should go into the /node.js/WorkingWithItems directory of the repo. Each call example should be in its own file.

**Comment by johanrin** [comment]
Next, I will start this one.
