### ISSUE TITLE
Node.js SDK - Example code for count, consumed capacity and consistent reads when using Query

### ISSUE THREAD

**Issue by synchrophoto** [synchrophoto/DynamoDB-SDK-examples#14]
Have an example file that has three things in it.

1. Examples of using ScannedCount and Count. 
2. An example where a query specifies the [ReturnConsumedCapacity](https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/Query.html#Query.CapacityUnits) to obtain information about that query's consumed capacity.
3. An example of a query with ConsistentRead = true.

Every query should have a check to see if LastEvaluatedKey is returned. We need to get developers in the habit of checking that.

These files should go into the /node.js/WorkingWithQueries/ directory.

**Comment by TLaue** [comment]
I take this one!

**Comment by johanrin** [comment]
@TLaue is it finished? Can we close this issue?

**Comment by TLaue** [comment]
@johanrin I have finished this task. It can be closed.
