### ISSUE TITLE
 Node.js - Examples using Query and various expression types 

### ISSUE THREAD

**Issue by synchrophoto** [synchrophoto/DynamoDB-SDK-examples#18]
Two examples:
- An example using FilterExpression
- An example using ProjectionExpression

These should go into /node.js/WorkingWithQueries/

**Comment by johanrin** [comment]
I'm closing this issue because PR already merged in #21

**Comment by johanrin** [comment]
I reopened this issue because the PR merged contains only the example with FilterExpression.

@DejanBelic I let you complete with the example with ProjectionExpression.
