### ISSUE TITLE
Node.js - Create CRUD operations examples with the Node.js SDK

### ISSUE THREAD

**Issue by synchrophoto** [synchrophoto/DynamoDB-SDK-examples#2]
Create an example for each of the following CRUD operations using the Node.js SDK.

- Delete item
- Get Item
- Put item
- Put item conditional
- Update item
- Update item conditional

Place all files under /node.js/WorkingWithItems/*

Please write the examples as if you were someone new to DynamoDB and this would be the kind of example that you'd want to read and would be helpful. The more comments in the code, the better.

**Comment by johanrin** [comment]
I would like to start with this one.

**Comment by synchrophoto** [comment]
Good question. I am not sure. How about you, @TLaue , and I discuss here real quick so all of the node.js code is similar?
