### ISSUE TITLE
Node.js - Create Global Table operations code examples using the AWS Node.js SDK

### ISSUE THREAD

**Issue by synchrophoto** [synchrophoto/DynamoDB-SDK-examples#3]
Create the following global table example code files where each of the following is a separate file:
- Create global table
- Add global table region
- Delete global table region
- Describe global table and describe the GT settings.
- Update global table and update the table's settings

Commit files in /node.js/WorkingWithTable/* directory.

**Comment by johanrin** [comment]
I take this one!
