### ISSUE TITLE
Golang - Create code examples for table level operations with the Go SDK

### ISSUE THREAD

**Issue by synchrophoto** [synchrophoto/DynamoDB-SDK-examples#5]
Create code examples for the following table level operations:

- Create table in provisioned capacity mode
- Create table in on-demand capacity mode
- Change table's provisioned capacity to add more capacity.
- Enable auto-scaling on a table set to provisioned capacity
- Update auto-scaling settings on a table set to provisioned capacity
- Disable auto-scaling on a provisioned capacity mode
- Describe limits
- Describe table
- List tables
- Change provisioned capacity mode table to on-demand mode
- Change on-demand mode table to provisioned and then add auto-scaling policy
- Enable streams on a table
- Delete a table

**Comment by jprivillaso** [comment]
Can you assign this to me, please?

**Comment by synchrophoto** [comment]
Done.

**Comment by jprivillaso** [comment]
You can close this issue since it has been already merged!

**Comment by synchrophoto** [comment]
Closing per @jprivillaso
