### ISSUE TITLE
Golang - Create Global Table operations code examples using the AWS Go SDK

### ISSUE THREAD

**Issue by synchrophoto** [synchrophoto/DynamoDB-SDK-examples#6]
Create the following global table example code files where each of the following is a separate file:
- Create global table
- Add global table region
- Delete global table region
- Describe global table and describe the GT settings.
- Update global table and update the table's settings

Commit files in /golang/WorkingWithTable/* directory.

**Comment by jprivillaso** [comment]
@synchrophoto @johanrin Please assign this issue to me

**Comment by synchrophoto** [comment]
Assigned!

**Comment by jprivillaso** [comment]
https://github.com/synchrophoto/DynamoDB-SDK-examples/pull/75

**Comment by synchrophoto** [comment]
Merged and closing this issue.

**Comment by synchrophoto** [comment]
Thank you @jprivillaso
