### ISSUE TITLE
Create transactions example, but in Node.js

### ISSUE THREAD

**Issue by synchrophoto** [synchrophoto/DynamoDB-SDK-examples#73]
Create the exact same sample code for this page https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/transaction-example.html but in Node.js

**Comment by tywalch** [comment]
Is this still needed? I see we have these two files already done:

https://github.com/synchrophoto/DynamoDB-SDK-examples/blob/master/node.js/WorkingWithItems/transact-write.js
https://github.com/synchrophoto/DynamoDB-SDK-examples/blob/master/node.js/WorkingWithItems/transact-get.js

Or maybe this ticket is to create matching examples to pair with the ones included on that exact page?

**Comment by synchrophoto** [comment]
@tywalch You are correct. It is not needed. somehow I missed those files.
