### ISSUE TITLE
Create parallel scan example in Node.js

### ISSUE THREAD

**Issue by synchrophoto** [synchrophoto/DynamoDB-SDK-examples#77]
Create an example of doing a parallel scan in node.js
https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/Scan.html#Scan.ParallelScan

**Comment by tywalch** [comment]
I put something something for this. This would be my first contribution here, and I'd like to keep with convention, is there a preferred file name and is it best to simply create a PR that references this Issue?

**Comment by synchrophoto** [comment]
What you did is exactly what we are looking for. Thank you!

On August 16, 2020 at 7:56:04 PM, Tyler W. Walch (notifications@github.com)
wrote:

I put something something for this. This would be my first contribution
here, and I'd like to keep with convention, is there a preferred file name
and is it best to simply create a PR that references this Issue?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/synchrophoto/DynamoDB-SDK-examples/issues/77#issuecomment-674629348>,
or unsubscribe
